export const data = [
	{
		key: 1,
		id: '1',
		name: 'Keyboard Kumara',
		code: '23415125415',
		price: 14.99,
		category: 'Tech',
		business: 'Innova',
		brand: 'Redragon',
		provider: 'Redragon',
		isOnPromotion: true,
		promotionPrice: 11.99,
		stock: 15,
	},
	{
		key: 2,
		id: '2',
		name: 'Mouse',
		code: '23415125415',
		price: 14.99,
		category: 'Tech',
		brand: 'Redragon',
		business: 'Innova',
		provider: 'Redragon',
		isOnPromotion: false,
		promotionPrice: 11.99,
		stock: 10,
	},
	{
		key: 3,
		id: '3',
		name: 'Mouse',
		code: '23415125415',
		price: 14.99,
		category: 'Tech',
		brand: 'Redragon',
		business: 'Innova',
		provider: 'Redragon',
		isOnPromotion: false,
		promotionPrice: 11.99,
		stock: 10,
	},
	{
		key: 4,
		id: '4',
		name: 'Mouse',
		code: '23415125415',
		price: 14.99,
		category: 'Tech',
		brand: 'Redragon',
		business: 'Innova',
		provider: 'Redragon',
		isOnPromotion: false,
		promotionPrice: 11.99,
		stock: 10,
	},
];
